services:
  pgdb:
    image: bitnami/postgresql:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=pgdb
    volumes:
      - pgdbdata:/var/lib/postgresql/data
  app:
      build: .
      ports:
        - '3333:3333'
        - '5555:5555'
      depends_on:
        - pgdb
      environment:
        - DATABASE_URL=postgresql://docker:docker@pgdb:5432/transactionsDB
        - NODE_ENV=dev
        - PORT=3333
      volumes:
        - .:/app
        - /app/node_modules

volumes:
  pgdbdata: